### ISSUE TITLE
Use uniform batch scripts

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/GoogleSignIn#14]
Use uniform batch scripts as presented in https://starcounter.gitbooks.io/guidelines/content/batch-files.html

Discussion: https://github.com/Starcounter/Guidelines/issues/6

**Comment by warpech** [comment]
Some projects output the exe files to `./bin/Debug` instead of `./src/<appname>/bin/Debug`.

The latter form is expected (see https://starcounter.gitbooks.io/guidelines/content/project_structure.html)

If this solution does not output the exe files to the desired paths (both in msbuild and in VS), please fix that immediately too.

**Comment by Mackiovello** [comment]
Fixed with c48cb2da250a7a740621a337605cd8974cd652cf and c48cb2da250a7a740621a337605cd8974cd652cf

**Comment by KmaTTi89** [comment]
Done in https://github.com/StarcounterApps/GoogleSignIn/pull/15
